### ISSUE TITLE
`Cannot read properties of null (reading 'path')` when selecting a note set

### ISSUE THREAD

**Issue by stefanherzog** [dartungar/obsidian-simple-note-review#12] opened 2022-10-16 15:07 UTC
Hi! Since I upgraded to Obsidian 1.0.0 I'm getting the error

```
Cannot read properties of null (reading `path`)
```

when I select a note set. Two days ago I somehow got it back to work (I've re-installed your plugin and did tried some other things), but I couldn't say what it was. The error message sounds like it's a problem with dataview(js). Any ideas what this is about?

**Comment by dartungar** [comment] 2022-10-17 06:39
Thanks for the report! I've reproduced it, will try to fix this as soon as possible since it's pretty nasty.

**Comment by stefanherzog** [comment] 2022-10-17 08:59
Thanks!
One weird insight: When I got the error, one thing that seemed to fix it was to ask the [spaced repetition plugin](https://www.google.com/search?q=spaced+repetition+obsidian+plugin) (which I'm also using) to review the next note. Then going back to your plugin, asking for the next note worked fine. I think I've reproduced this twice, not sure what it means.

**Comment by kmaustral** [comment] 2022-12-23 06:40
I'm getting this error now too. I don't know what caused it.

**Comment by efemkay** [comment] 2022-12-30 02:27
just dropping a note that i also faced with this issue.

**Comment by dartungar** [comment] 2022-12-30 05:33
@efemkay @kmaustral So far I wasn't able to reproduce this error. It would help if you provide specifics of the note set you are having trouble with: does it use folders, tags, or both? A screenshot would do just fine, like that:
![image](https://user-images.githubusercontent.com/36126057/210037958-0f8d6aed-8c1f-4deb-b8e4-5cb1a89155f1.png)

**Comment by dartungar** [comment] 2022-12-30 05:48
https://github.com/dartungar/obsidian-simple-note-review/releases/tag/0.5.9 should help with this error, but please provide the screens anyway!

**Comment by efemkay** [comment] 2022-12-30 13:01
awesome! the latest update fixed that. anyhow, below is the plugin settings (for both before and after the update), which the update fixed the issue. fyi, i intend to review my notes with `#PermanentNote` but i added any notes from folder "Areas" just widen the coverage (in case that is an issue)

![image](https://user-images.githubusercontent.com/42369515/210072524-6d7ce456-eee9-44c4-923b-9d645c33defc.png)

**Comment by dartungar** [comment] 2023-01-02 17:17
Okay, I've reproduced this bug in one case:
- open note set
- delete the note
- try to open any note set again
The bug is probably due to Dataview unable to get current note's path (since it is deleted), I will look into how to fix that properly.

**Comment by dartungar** [comment] 2023-01-03 05:55
Hopefully, this is fixed in v0.5.10.

**Closed by dartungar** 2023-01-03 05:55 UTC
Labels: bug
