### ISSUE TITLE
`cannot read properties of undefined (reading "index")`

### ISSUE THREAD

**Issue by stefanherzog** [dartungar/obsidian-simple-note-review#20] opened 2022-11-02 08:08 UTC
When I try to mark a note as reviewed today, I get `cannot read properties of undefined (reading "index")`. Restarting the app doesn't help, neither does doing something with the spaced repetition plugin (which [helped with another bug with a similar error message](https://github.com/dartungar/obsidian-simple-note-review/issues/12#issuecomment-1280520353)).

- Obsidian Version 1.0.3 (Installer 1.0.0)
- Simple Note Review 0.5.7
- macOS 10.15.7

**Comment by stefanherzog** [comment] 2022-11-02 08:12
BTW

- changing the review-frequency works fine for me.
- But selecting the next note to review does not work. I get an API error which also tells me to disable then enable the plugin. This also fixed the above bug, I can now mark a note as reviewed today.

**Comment by dartungar** [comment] 2022-11-02 10:16
@stefanherzog Huh, so far I can't reproduce it. Sounds like it's connected to Dataview. Is there a stack trace in log (precc CTRL+SHIFT+I to open console/log)?

**Comment by stefanherzog** [comment] 2022-11-03 15:03
@dartungar : I couldn't find a trace (presumably because after disabling/re-enabling the plugin it worked again).

**Comment by dartungar** [comment] 2022-11-16 10:16
I'll close this for now, please tell if this pops up again.

**Closed by dartungar** 2022-11-16 10:16 UTC
Labels: bug
